### ISSUE TITLE
Improvements in Readme.md

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#1]

**Comment by Chanchal-D** [comment]
I can make the readme more interactive and descriptive

**Comment by UjjwalSharma01** [comment]
Go ahead

**Comment by Chanchal-D** [comment]
yes

**Comment by UjjwalSharma01** [comment]
Great job! If you have more contributions in mind or any questions, feel free to open new issues or PRs. Keep up the good work! 👏
