### ISSUE TITLE
[BUG] Fix the quote-title area

### ISSUE THREAD

**Issue by Geeks-Arpan** [UjjwalSharma01/checklist#123]
![Checklist](https://github.com/UjjwalSharma01/checklist/assets/99377659/5f39dd0d-38bf-466f-9ed5-148ddb7399b9)

Assign me Under Apertre'24

**Comment by UjjwalSharma01** [comment]
Go ahead @Geeks-Arpan

**Comment by YooAshu** [comment]
@UjjwalSharma01 as this is not fixed yet , I want to work on this

**Comment by UjjwalSharma01** [comment]
Go ahead @YooAshu
