### ISSUE TITLE
[Feature] Add more frontend Projects in Frontend Project section

### ISSUE THREAD

**Issue by Geeks-Arpan** [UjjwalSharma01/checklist#124]
Assign me under Apertre'24

**Comment by AnitSarkar123** [comment]
Also Please, Assign me under Apertre'24.I want to contribute Three frontend project

**Comment by UjjwalSharma01** [comment]
go ahead @Geeks-Arpan

**Comment by YooAshu** [comment]
I would like to work on this after I submit PR of my previous issues on this repo
