### ISSUE TITLE
[Feature] Modifying the "Contact" section

### ISSUE THREAD

**Issue by yaten2302** [UjjwalSharma01/checklist#13]
Hi @UjjwalSharma01, I would like to modify the UI of the contact section, so as to make it more attractive.
Please assign this issue to me.
<br>
![image](https://github.com/UjjwalSharma01/checklist/assets/129659514/39650a5b-e854-41b3-b05c-0181c3adb517)

**Comment by UjjwalSharma01** [comment]
Go ahead @yaten2302

**Comment by UjjwalSharma01** [comment]
you are working on this @yaten2302 ?

**Comment by yaten2302** [comment]
Sorry for the late PR @UjjwalSharma01, I've now created the PR, could you please review and merge it.

**Comment by UjjwalSharma01** [comment]
> Sorry for the late PR @UjjwalSharma01, I've now created the PR, could you please review and merge it.

Check my comment on PR
