### ISSUE TITLE
The topic wise page does not contain footer

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#135]
Most of the learning website have their footer section for each page. So, we need to add footer in the topics page of this website 
![Screenshot from 2024-01-10 12-35-57](https://github.com/UjjwalSharma01/checklist/assets/97402824/eb594ca0-7f58-45f8-8762-4c7ad611267a)

Kindly review my Issue and assign me under apertre24.

**Comment by UjjwalSharma01** [comment]
Go ahead

**Comment by rko0211** [comment]
Hey i would make footer for all pages so it should be medium issue...

**Comment by UjjwalSharma01** [comment]
> Hey i would make footer for all pages so it should be medium issue... 

Read the rules
