### ISSUE TITLE
Contact us form need to be validated before submission

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#146]
Hey In the contact form we should use Javascript form validation features so that user gives correct information. 

![Screenshot_2024-01-12-16-50-57-911_com android chrome](https://github.com/UjjwalSharma01/checklist/assets/97402824/b02d2200-f4ba-46ec-bf4d-087fb6421852)

**Comment by UjjwalSharma01** [comment]
Go ahead
