### ISSUE TITLE
Add Some more API boxes : update README.md

### ISSUE THREAD

**Issue by apu52** [UjjwalSharma01/checklist#147]
**Describe the feature you are requesting**

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges
It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.
**Additional context(if any)**

![image](https://github.com/UjjwalSharma01/checklist/assets/114172928/2c535c00-107f-49d1-b122-63ceeb741181)

***Are you contributing under any open-source program ?***

APERTRE'24

**Comment by apu52** [comment]
@UjjwalSharma01 Please assign me this issue under APERTRE'24

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 Please assign me this issue under APERTRE'24

Necessary badges are already there

**Comment by apu52** [comment]
@UjjwalSharma01 Can I still work on this issue??

**Comment by UjjwalSharma01** [comment]
> @UjjwalSharma01 Can I still work on this issue??

No
