### ISSUE TITLE
Add a Navigation bar

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#15]
- try to make it responsive
- shift the buttons, Contact Us and Contribute to the navigation bar

**Comment by Milind-Palaria** [comment]
hey @UjjwalSharma01 can you assign me?

**Comment by UjjwalSharma01** [comment]
You will do both things at the same time, CSS and this?

**Comment by anu7701** [comment]
Can you assign it to me?

**Comment by UjjwalSharma01** [comment]
@Milind-Palaria you already got the task for the CSS for the website buddy, so we can assign this to @anu7701 

go ahead anu

try to make the task bar responsive

**Comment by anu7701** [comment]
Can you please specify the enhancements you want, since Contact Us and Contribute are already inside a nav bar

**Comment by UjjwalSharma01** [comment]
We're in need of a responsive navigation bar that adapts to different screen sizes. On smaller screens, it should feature a toggle button (commonly referred to as the 'hamburger' menu) on the left, with the title in the middle of the screen in an appropriate size. On larger screens, it should appear on the left side of the screen, showcasing sections for 'Contact Us,' 'Contribute,' and name, let us know if you have more questions regarding this

**Comment by UjjwalSharma01** [comment]
@anu7701 working on it?

**Comment by Milind-Palaria** [comment]
hey @UjjwalSharma01 i have completed your previous issues, since your assignee is not working on this one you can assign me this, and elaborate what you want in your nav bar.

**Comment by anu7701** [comment]
I am still working on it

**Comment by UjjwalSharma01** [comment]
@anu7701 any update??

**Comment by anu7701** [comment]
made a pull request, please review

**Comment by inviBeast** [comment]
I want to work on this @UjjwalSharma01

**Comment by RP2025** [comment]
Assign me this issue please
i will complete it by 22nd October End of the Day
Thankyou

**Comment by UjjwalSharma01** [comment]
> Assign me this issue please
> i will complete it by 22nd October End of the Day
> Thankyou

Go ahead

**Comment by UjjwalSharma01** [comment]
any update @RP2025 ?

**Comment by kalkeshwar** [comment]
@UjjwalSharma01  hey if the work has not yet done? Assign to me I will work on it as I  have worked previous on same type of issue.

**Comment by UjjwalSharma01** [comment]
@kalkeshwar go ahead
