### ISSUE TITLE
ADD Sign in and sign up form in this website 

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#150]
As most of the learning website has sign in and sign up form, so i think you have to add this with the website.

Kindly think about this issue and assign me under apertre24. Thank you..

**Comment by UjjwalSharma01** [comment]
but there is no use of sign in or sign up as such

**Comment by rko0211** [comment]
Actually when user visit your website they may create their account like GFG, W3school like such website and for that we can build this part as frontend

**Comment by UjjwalSharma01** [comment]
> Actually when user visit your website they may create their account like GFG, W3school like such website and for that we can build this part as frontend

I get you buddy but there is no use as such of that feature within the website because we are not storing any kind of information or giving any personalisation

**Comment by rko0211** [comment]
Ok no problem
