### ISSUE TITLE
Adding some animation on scroll

### ISSUE THREAD

**Issue by 123shreyanvi** [UjjwalSharma01/checklist#151]
Adding scroll animation feature will make it UI more attractive to the user

**Comment by UjjwalSharma01** [comment]
go ahead

**Comment by 123shreyanvi** [comment]
> Could you assign me this task?

It's done already

**Comment by rko0211** [comment]
Int is not Scroll back button, it just refresh the webpage.

**Comment by 123shreyanvi** [comment]
> It is not Scroll back button, it just refresh the webpage.

nops it is take a look at the code  plus I was talking about the animation on scroll issue

**Comment by 123shreyanvi** [comment]
well i was talking about the animation part
