### ISSUE TITLE
Font enhancement 

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#154]
The current font used in the website is not good for readability that must decreases user experience, I can change this font,

![Screenshot from 2024-01-15 02-43-03](https://github.com/UjjwalSharma01/checklist/assets/97402824/bd3ffc32-7c51-4d0c-8c00-bbb15816c401)

**Comment by UjjwalSharma01** [comment]
go ahead

**Comment by UjjwalSharma01** [comment]
font is improved now

**Comment by rko0211** [comment]
Kindly check font is not improved in the hosted website..
