### ISSUE TITLE
Adding a get in touch button  and scroll to Top arrow button instead of back to top division 

### ISSUE THREAD

**Issue by 123shreyanvi** [UjjwalSharma01/checklist#164]
Adding get in touch button and connecting it to google sheets 
adding a Arrow button at the bottom right for scrolling up It will enhance the UI

**Comment by 123shreyanvi** [comment]
Do assign me this

**Comment by UjjwalSharma01** [comment]
go ahead

**Comment by 123shreyanvi** [comment]
Ok
