### ISSUE TITLE
Problem with "Back To Top" Option in Footer of all pages 

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#176]
![Screenshot_2024-01-19-03-16-01-558_com android chrome](https://github.com/UjjwalSharma01/checklist/assets/97402824/57810311-bf8b-4cc6-8927-5c7ff088b76a)

**Comment by PunugupatiSaikumar** [comment]
I can work on this, can you assign this to me and can you give a little bit of description about the issue.
Thank you

**Comment by UjjwalSharma01** [comment]
Go ahead @rko0211
