### ISSUE TITLE
Contact us and contribute here was not visible in mobile view 

### ISSUE THREAD

**Issue by Sneha123-zudo** [UjjwalSharma01/checklist#177]

**Comment by Sneha123-zudo** [comment]
![Screenshot_2024-01-19-12-24-38-67](https://github.com/UjjwalSharma01/checklist/assets/145490348/726b9e2f-06d8-4d2b-a7ff-ee6f1332f4c6)
Please assign me this issue

**Comment by Sneha123-zudo** [comment]
![IMG_20240119_122552](https://github.com/UjjwalSharma01/checklist/assets/145490348/1509993d-b263-4837-a4fc-2754c256704c)
Please assign me this issue

**Comment by UjjwalSharma01** [comment]
If you click menu it will.appear
