### ISSUE TITLE
Add beautiful and responsive Footer in About Page

### ISSUE THREAD

**Issue by rko0211** [UjjwalSharma01/checklist#186]
There should be an beautiful footer in About page. Kindly assign me this issue.

**Comment by UjjwalSharma01** [comment]
The definition of beautiful is different for everybody, please state the changes you want to make

**Comment by rko0211** [comment]
Ok, I would create an footer in which there would be some heading about this site like options that the website provide and social mesia icon of owner and organization and copy right text.

**Comment by UjjwalSharma01** [comment]
Go ahead
