### ISSUE TITLE
Improve the UI for mobile or similar screens

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#21]
fix the font size and the other elements for the smaller screens accordingly

**Comment by Tejaswi293** [comment]
Hello, could you assign this issue to me? I'll try working on it!

**Comment by UjjwalSharma01** [comment]
@Tejaswi293 
 we've already assigned you the task for logo design, you can get only one issue at once, you can take up this one after completing logo

**Comment by Tejaswi293** [comment]
Okay, sir I'll work on that one first.

**Comment by Milind-Palaria** [comment]
@UjjwalSharma01 can you assign me this?

**Comment by UjjwalSharma01** [comment]
@Milind-Palaria go ahead

**Comment by UjjwalSharma01** [comment]
Any update @Milind-Palaria

**Comment by inviBeast** [comment]
Hey @UjjwalSharma01 It would be really great if you could assign me this issue. I am highly interested in contributing to this project and major people are inactive so please assign me the issues.

**Comment by UjjwalSharma01** [comment]
@inviBeast you can start working on this issue, we can assign the other issues once you finish the assigned one 😊

**Comment by inviBeast** [comment]
thanks
