### ISSUE TITLE
Enhancement: Allow sections to be expanded by clicking on highlighted section

### ISSUE THREAD

**Issue by kliu57** [UjjwalSharma01/checklist#24]
I have a proposed enhancement for the **C++ and OOP pages**, to allow users to expand sections by clicking on the highlighted section rather in addition to clicking on the arrow. I feel it is more intuitive for first-time users; also because the highlighting of the section makes the user think that it is a clickable element. See images below:

![screenshot1](https://github.com/UjjwalSharma01/checklist/assets/98062538/d62a94bb-7821-4b40-a9ed-0a0065380e8c)
![screenshot2](https://github.com/UjjwalSharma01/checklist/assets/98062538/80c40272-0ff3-4695-be33-fe68788b34f3)

@UjjwalSharma01 If you are ok with this enhancement, could you please assign it to me? Thank you.

**Comment by UjjwalSharma01** [comment]
@kliu57 go ahead

**Comment by kliu57** [comment]
@UjjwalSharma01 I have made a pull request, please review when you have time. Thank you!
