### ISSUE TITLE
Add other topics

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#25]
You can also add any language or tech stack if you feel confident about it and can explain it in the easiest way with examples

**Comment by mayankch283** [comment]
Hello. I'd like to take a chance on this one.
I'm confident I can explain the basics of web development and web app architecture and would like to contribute on the same.Please assign this to me.

**Comment by UjjwalSharma01** [comment]
Go ahead, @mayankch283 , make sure to add relevant examples and code snippets wherever required

**Comment by dpvasani** [comment]
i would like to add mongodb resourcees

**Comment by UjjwalSharma01** [comment]
Go ahead, @dpvasani  , make sure to explain in the simplest language possible, add relevant examples and code snippets wherever required
