### ISSUE TITLE
Want to add content in OOPS 

### ISSUE THREAD

**Issue by Vanraj8169** [UjjwalSharma01/checklist#28]
Hey @UjjwalSharma01 please assign me this issue. 
        I have already added two topics. 
Assign me to add more. 
Thanking you!

**Comment by UjjwalSharma01** [comment]
go ahead, and the entire content of the OOP will be merged only in one PR, use simplest language to explain the concepts, use references, examples and code snippets, wherever required and strict no use of AI

**Comment by Vanraj8169** [comment]
Ok
