### ISSUE TITLE
Want to add back button 

### ISSUE THREAD

**Issue by pra9patil** [UjjwalSharma01/checklist#36]
Hey @UjjwalSharma01  Sir ,
How are you doing , I hope you doing well
After going through The Checklist website I realized that after opning particular section there is no any back option ,
For example If I open C++ basics page and I want to back to home Page then there is no option for it 
So will you assign me this issue so I can work on it using simple HTML , CSS and JavaScript 
Under Hactoberfest .

Thank You

**Comment by UjjwalSharma01** [comment]
> Hey @UjjwalSharma01  Sir ,
> How are you doing , I hope you doing well
> After going through The Checklist website I realized that after opning particular section there is no any back option ,
> For example If I open C++ basics page and I want to back to home Page then there is no option for it 
> So will you assign me this issue so I can work on it using simple HTML , CSS and JavaScript 
> Under Hactoberfest .
> 
> Thank You

You can go back by clicking on the name of website i.e __The Checklist__

**Comment by pra9patil** [comment]
Ok sorry sir , I can't figure it out at that time .
Sir then I can add footer section in website with 3 Main section in it 
1) Contact Us
2) follow us 
3) Team
4) Copy right 
will you assign me this issue so I can work on it as soon as possible.

**Comment by UjjwalSharma01** [comment]
i don't think we need a footer right now, please find  some other issue to work on
