### ISSUE TITLE
Add Content in OOP

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#5]

**Comment by HKABIG** [comment]
I would like to work on this
Can you please assign this to me

**Comment by Chanchal-D** [comment]
i would like to add content in OOPs and make changes in it.

**Comment by UjjwalSharma01** [comment]
@Chanchal-D 
you already got the task of README.md file, so we can assign this to @HKABIG

**Comment by UjjwalSharma01** [comment]
@HKABIG working on it?

**Comment by HKABIG** [comment]
You can unassign me if someone else is interested

**Comment by UjjwalSharma01** [comment]
sure
