### ISSUE TITLE
addition of Python & C# basics

### ISSUE THREAD

**Issue by aditya4567uk** [UjjwalSharma01/checklist#50]
Hi

I can add some concepts of Python 3 & C# Language
additionally I can do a little design change in content section , everything in concept title(C++ BASICS etc..) is aligned in very left so according to design and user visibility perspective we can do it center ; IT WILL LOOK MUCH BETTER :)

Could you you pls let me contribute/assign to this issue? that's ALL HAPPY CODING :)

**Comment by UjjwalSharma01** [comment]
Go ahead, make sure to use the simplest language possible with code snippets, references and examples wherever required and strict no use of AI otherwise the PR will be marked as SPAM

**Comment by aditya4567uk** [comment]
sure thing !

**Comment by Chanchal-D** [comment]
can i work on this?

**Comment by RP2025** [comment]
Assign me this issue please
i will complete it by 22nd October End of the Day
Thankyou

**Comment by aditya4567uk** [comment]
@RP2025 @Chanchal-D i have already done the task 2days ago.. I'm waiting for merge.

**Comment by aditya4567uk** [comment]
@UjjwalSharma01 could you plz look into pull request and merge the code, as there are not conflicts and tests are passed.. All looks green, 

And yes I have included python very well, I'll be adding more content to it. 

Thanks.
