### ISSUE TITLE
Add content for javascript 

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#64]
Make sure to use simple, language, examples and code snippets wherever required

USAGE OF AI IS STRICTLY NOT ALLOWED

**Comment by dpvasani** [comment]
assign to me

**Comment by dpvasani** [comment]
make sure to add Hacktoberfest label

**Comment by dpvasani** [comment]
i have been made code for this assign  to me as soon as possible

**Comment by UjjwalSharma01** [comment]
> make sure to add Hacktoberfest label

please be polite to all the maintainers
