### ISSUE TITLE
Add content for c

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#65]
Make sure to use simple, language, examples and code snippets wherever required

USAGE OF AI IS STRICTLY NOT ALLOWED

**Comment by Panda-Abhisek** [comment]
I wanna work on this issue. Can you please assign this to me under Hacktoberfest?

**Comment by UjjwalSharma01** [comment]
> I wanna work on this issue. Can you please assign this to me under Hacktoberfest?
> 
Go ahead
Make sure to adhere to the instructions given, use code snippets using code tag
Mention your issue number with a hashtag in the PR 
No use of AI
Proper definition and examples and all the basic topics should be covered properly

**Comment by RP2025** [comment]
Assign me this issue please
i will complete it by 22nd October End of the Day
Thankyou
