### ISSUE TITLE
All checkboxes being ticked on refresh, after a checkbox was ticked

### ISSUE THREAD

**Issue by sikehish** [UjjwalSharma01/checklist#70]
![image](https://github.com/UjjwalSharma01/checklist/assets/90673701/90afa56b-8c88-461e-aeb6-4ebd34a9face)
I checked one of the boxes, and after refreshing, both the check boxes were ticked.

**Comment by UjjwalSharma01** [comment]
@sikehish fix the issue

**Comment by hamzailyas237** [comment]
I have solved the issue. Please assign it to me under hactoberfest.

**Comment by sikehish** [comment]
I dont think Ill be able to work on it. You can assign it to someone else
