### ISSUE TITLE
Adding Content for Go Lang Basics 

### ISSUE THREAD

**Issue by RP2025** [UjjwalSharma01/checklist#76]
I want to add some more content for Go Lang Basics 
Kindly let me know if i can go ahead with this issue for hacktober fest 

Thanks
Regards

**Comment by UjjwalSharma01** [comment]
go ahead, make sure to add simplest explanations, with examples and code snippets , under __code__ tag, check _GFG_ website for the reference, 

strict no USAGE OF AI, OTHERWISE THE PR WILL BE MARKED AS SPAM

**Comment by UjjwalSharma01** [comment]
any update @RP2025 ?
