### ISSUE TITLE
fix the bug of darkmode icon

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#8]
fix the Overlapping of icons while dark mode is on
![reference](https://github.com/UjjwalSharma01/checklist/blob/c7f2cc55439ee5165e8d8fe300426b2be61dba92/Bugs/Images/bug.PNG)

**Comment by HKABIG** [comment]
I have fixed this bug

**Comment by HKABIG** [comment]
Added the bug fixes in in the initial pull request only
Please review it for Merging
