### ISSUE TITLE
Improving the Contact Page of the Website 

### ISSUE THREAD

**Issue by Karansankhe** [UjjwalSharma01/checklist#84]
Please assign me these issue under hacktoberfest2023 for Improving the Contact Page of the Website

**Comment by UjjwalSharma01** [comment]
what improvements you want to make, to be precise, please explain that

**Comment by Karansankhe** [comment]
improving the Ui, keeping the redirect to the home page.

**Comment by AnitSarkar123** [comment]
improving the Ui, keeping the redirect to the home page.Assign me under Apertre'24
