### ISSUE TITLE
Adding CSS Notes

### ISSUE THREAD

**Issue by rover07** [UjjwalSharma01/checklist#93]
I will add CSS notes which will be short and good for quick revision.

**Comment by UjjwalSharma01** [comment]
Make sure to add proper crisp explanation, with code snippets 

No use of AI

**Comment by rover07** [comment]
Sure. My notes were large so I used AI to make the same in short and concise, no other use apart from that.

**Comment by rover07** [comment]
I have not mentioned code snippets in recent PR's, so I will fix that and make another PR soon!

**Comment by Mstanic05** [comment]
Can you assign this to me!

**Comment by kalkeshwar** [comment]
@UjjwalSharma01  is this repo excluded from hacktoberfest or it will be accepted?

**Comment by AnitSarkar123** [comment]
I   I want to add CSS nots ,Assign me under Apertre'24
